spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: cnmg3333
    timeout: 5000

mysqlRoot: root
mysqlPassword : Joe20131215!.
mysqlUrl: jdbc:mysql://47.104.245.206:3306/cartools?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false