spring:
  datasource:
    druid:
    #   数据源基本配置
    username: cartool
#    password: GoodLuck!APP20
    password: Car.2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.87.189.181:3306/cartools?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  http:
    multipart:
      max-file-size:100Mb
      max-request-size:100Mb
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.example.tools.entity
  mapper-locations: classpath:mapper/*.xml


# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false # 如果没有数据  返回空 而非最后一页的数据
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

server:
  port: 8080