server:
  port: 8008
spring:
  profiles:
    active: dev
  application:
    name: godtools
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #   数据源基本配置
      username: ${mysqlRoot}
      #    password: GoodLuck!APP20
      password: ${mysqlPassword}
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${mysqlUrl}
      initial-size: 5
      #   数据源其他配置
      minIdle: 5
      maxActive: 30
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 100MB
  redis:
    host: ${redisHost}
    port: ${redisPort}
    password: ${redisPassword}
    timeout: 5000

logging:
  file:
    path: ./_log/${spring.application.name}
  level:
    com.hyll.godtools.mapper: debug
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hyll.godtools.pojo.**
  configuration:
    cache-enabled:  false
    lazy-loading-enabled: false
    default-statement-timeout:  20000
    aggressive-lazy-loading:  false
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false # 如果没有数据  返回空 而非最后一页的数据
  supportMethodsArguments: true
  params: count=countSql


jetcache:
  statIntervalMinutes:  15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}