redisHost: 127.0.0.1
redisPassword: cnmg3333
redisPort: 6379
mysqlRoot: root
mysqlPassword : Joe20131215!.
mysqlUrl: jdbc:mysql://47.104.245.206:3306/cartools?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false